### ISSUE TITLE
tests fail on my (Galen's) mac

### ISSUE THREAD

**Issue by joefowler** [usnistgov/mass#122]
**[Original report](https://bitbucket.org/joe_fowler/mass/issues/122) by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

Despite passing on the CI, they fail on my mac. One has to do with a key for looking up the MnKalpha energy, and the rest have to do with LaplaceEntropy (numpy version? I have 1.12.1).

```
======================================================================
FAIL: test_bug116 (test_entropy.Test_LaplaceEntropy)
See MASS issue #116: nonsense values are STILL appearing in KL divergence.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 171, in test_bug116
    self.assertLess(abs(D), 20)
AssertionError: 10422227644.294964 not less than 20

======================================================================
FAIL: test_exact_approx_cross_entropy (test_entropy.Test_LaplaceEntropy)
Test the exact vs approximated modes of laplace_cross_entropy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 102, in test_exact_approx_cross_entropy
    self.assertAlmostEqual(e, 1.94136653687)
AssertionError: 1.806484673804412 != 1.94136653687 within 7 places

======================================================================
FAIL: test_specific_values_crossH (test_entropy.Test_LaplaceEntropy)
Cross-entropy on some specific values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 59, in test_specific_values_crossH
    self.assertAlmostEqual(e, 2.34308882742)
AssertionError: 2.0610266217313877 != 2.34308882742 within 7 places

======================================================================
FAIL: test_types (test_entropy.Test_LaplaceEntropy)
Make sure entropy works when inputs are not float64.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 149, in test_types
    self.assertAlmostEqual(e, 1.39061512214)
AssertionError: 1.2816928551002664 != 1.39061512214 within 7 places

----------------------------------------------------------------------
Ran 105 tests in 17.087s

FAILED (failures=4, errors=1)
```

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

This apparently leads to me failing to compute filters

```
data.compute_filters()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.6.0-py2.7-macosx-10.12-x86_64.egg/mass/core/channel.pyc in cost(slope, x, y)
   1041         # Now use min-entropy computation to model dp/dt on the rising edge
   1042         def cost(slope, x, y):
-> 1043             return mass.mathstat.entropy.laplace_entropy(y-x*slope, 0.002)
   1044 
   1045         peak_sample = sp.stats.mode(self.p_peak_index).mode[0]

src/mass/mathstat/entropy.pyx in mass.mathstat.entropy.laplace_entropy (src/mass/mathstat/entropy.c:2155)()

src/mass/mathstat/entropy.pyx in mass.mathstat.entropy.laplace_entropy (src/mass/mathstat/entropy.c:1831)()

ValueError: laplace_entropy(x) needs at least 1 element in `x`.
```

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Galen: when you filed this issue, you didn't copy the error that you mentioned, the one from the line energies dictionary. I can't reproduce the error on my Mac, but perhaps I could at least fix the error you have if I could see the relevant traceback.

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

So I cannot find any issues on either of the Macs that I operate. Can you give me the specific commit? Can you get the latest from Develop and tell me whether you continue to have this problem?

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

Note git log call at the bottom for commit. The commit is actually brand new because I merged a docstring and figured it wasn't worth bothering you if it had accidentally been fixed.
```
/Users/oneilg/mass/runtests.py
found the following 16 modules to test:
<module 'test_time_drift_correction' from '/Users/oneilg/mass/src/mass/core/test_time_drift_correction.pyc'>
<module 'test_lines' from '/Users/oneilg/mass/src/mass/calibration/test_lines.pyc'>
<module 'test_robust' from '/Users/oneilg/mass/src/mass/mathstat/test/test_robust.pyc'>
<module 'test_special' from '/Users/oneilg/mass/src/mass/mathstat/test/test_special.pyc'>
<module 'test_entropy' from '/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.pyc'>
<module 'test_regression' from '/Users/oneilg/mass/src/mass/regression_test/test_regression.pyc'>
<module 'test_interpolation' from '/Users/oneilg/mass/src/mass/mathstat/test/test_interpolation.pyc'>
<module 'test_core' from '/Users/oneilg/mass/src/mass/core/test_core.pyc'>
<module 'test_calibration' from '/Users/oneilg/mass/src/mass/calibration/test_calibration.pyc'>
<module 'test_ljh_util' from '/Users/oneilg/mass/src/mass/core/test_ljh_util.pyc'>
<module 'test_fits' from '/Users/oneilg/mass/src/mass/calibration/test_fits.pyc'>
<module 'test_filtering' from '/Users/oneilg/mass/src/mass/core/test_filtering.pyc'>
<module 'test_algorithms' from '/Users/oneilg/mass/src/mass/calibration/test_algorithms.pyc'>
<module 'test_demos' from '/Users/oneilg/mass/src/mass/demo/test_demos.pyc'>
<module 'test_fitting' from '/Users/oneilg/mass/src/mass/mathstat/test/test_fitting.pyc'>
<module 'test_toeplitz' from '/Users/oneilg/mass/src/mass/mathstat/test/test_toeplitz.pyc'>
................F..F...F.F......WARNING: Chan 1 flagged bad because testing all channels bad
Testing printing of a TESGroup
TESGroup(pulse=src/mass/regression_test, noise=src/mass/regression_test)
../opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The spectral and spectral_r colormap was deprecated in version 2.0. Use nipy_spectral and nipy_spectral_r instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
../opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/signal/_peak_finding.py:412: RuntimeWarning: divide by zero encountered in double_scalars
  snr = abs(cwt[line[0][0], line[1][0]] / noises[line[1][0]])
.Testing printing of a TESGroupHDF5
TESGroupHDF5(hdf5_file=/Users/oneilg/mass/src/mass/regression_test/regress_mass.hdf5)
...............E............................./opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/figure.py:403: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
........................
======================================================================
ERROR: test_synonyms (test_calibration.TestLineDatabase)
Test that there are multiple equivalent synonyms for the K-alpha1 line.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/calibration/test_calibration.py", line 44, in test_synonyms
    self.assertEqual(e, E[name])
KeyError: 'MnKA'

======================================================================
FAIL: test_bug116 (test_entropy.Test_LaplaceEntropy)
See MASS issue #116: nonsense values are STILL appearing in KL divergence.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 171, in test_bug116
    self.assertLess(abs(D), 20)
AssertionError: 10422227644.294964 not less than 20

======================================================================
FAIL: test_exact_approx_cross_entropy (test_entropy.Test_LaplaceEntropy)
Test the exact vs approximated modes of laplace_cross_entropy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 102, in test_exact_approx_cross_entropy
    self.assertAlmostEqual(e, 1.94136653687)
AssertionError: 1.806484673804412 != 1.94136653687 within 7 places

======================================================================
FAIL: test_specific_values_crossH (test_entropy.Test_LaplaceEntropy)
Cross-entropy on some specific values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 59, in test_specific_values_crossH
    self.assertAlmostEqual(e, 2.34308882742)
AssertionError: 2.0610266217313877 != 2.34308882742 within 7 places

======================================================================
FAIL: test_types (test_entropy.Test_LaplaceEntropy)
Make sure entropy works when inputs are not float64.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oneilg/mass/src/mass/mathstat/test/test_entropy.py", line 149, in test_types
    self.assertAlmostEqual(e, 1.39061512214)
AssertionError: 1.2816928551002664 != 1.39061512214 within 7 places

----------------------------------------------------------------------
Ran 106 tests in 16.759s

FAILED (failures=4, errors=1)
687gombp:mass oneilg$ git log
commit 40e4710ab9d96ff0e07010783b1e30b8c46733ed
Merge: 17909ef 4634554
Author: ggggggggg <galenoneil@gmail.com>
Date:   Wed Jun 28 08:56:33 2017 -0600

    Merge branch 'develop' of bitbucket.org:joe_fowler/mass into develop
```

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Thanks. Even with commit 40e4710 I still cannot reproduce your error or the 4 test failures. I'm wondering if there's something funny in your installation? As in, maybe there are files installed that are no longer part of MASS, and their presence somehow screws up the module loading.

Let's look at the error first, because I cannot see what would be wrong other than some kind of import hiding another import. Can you reproduce the error at the REPL? I get the following, error-free:

```
#!python

In [157]: for name in ("MnKA", "MnKA1", "MnKL3", "MnKAlpha1"):
     ...:     print mass.STANDARD_FEATURES[name]
     ...:     
5898.801
5898.801
5898.801
5898.801

```

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

I'm going to add this to the v0.6 milestone, so that we figure this out and fix it before proceeding.

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

I re-ran `sudo python setup.py install` and now the tests pass. This makes it seem like I had just not installed, but I'm confident I tried reinstalling before reporting in the first place. But, who knows.

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

just reinstall?

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Removing milestone: v0.6 (automated comment)
