### ISSUE TITLE
Mass is failing 2 tests

### ISSUE THREAD

**Issue by joefowler** [usnistgov/mass#158]
**[Original report](https://bitbucket.org/joe_fowler/mass/issues/158) by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Fix this:

```text
======================================================================
FAIL: test_histogram_precision_bug (test_bugpatching.TestNumpyHistogramBug)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fowlerj/Software/mass/src/mass/mathstat/test/test_bugpatching.py", line 31, in test_histogram_precision_bug
    self.assertEqual(counts[0], 0)
AssertionError: 1.0 != 0

======================================================================
FAIL: test_post_filter (test_regression.TestSummaries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fowlerj/Software/mass/src/mass/regression_test/test_regression.py", line 86, in test_post_filter
    nt.assert_allclose(self.data.datasets[0].p_filt_value_dc, self.d['p_filt_value_dc'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1443, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 780, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 11.0%)
 x: array([13436.648 , 13314.329 , 13472.168 , 12154.449 , 13450.406 ,
       13452.018 , 13428.036 ,  7224.057 , 13445.055 , 12180.581 ,
       13445.557 , 13437.651 , 12325.465 , 13450.504 , 13465.    ,...
 y: array([13436.65  , 13314.33  , 13472.17  , 12154.45  , 13450.406 ,
       13452.018 , 13428.036 ,  7224.058 , 13445.057 , 12180.583 ,
       13445.559 , 13437.651 , 12325.465 , 13450.504 , 13465.    ,...

----------------------------------------------------------------------
Ran 130 tests in 32.641s

FAILED (failures=2)
```

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Removing milestone: v0.7 (automated comment)
