### ISSUE TITLE
2 automated tests fail

### ISSUE THREAD

**Issue by joefowler** [usnistgov/mass#76]
**[Original report](https://bitbucket.org/joe_fowler/mass/issues/76) by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

@oneilg has set up some automated tests. Nice! But two of them fail on most machines that I have tried, including (now) my laptop.

I'm working on this now, and perhaps I'll find it easy. But if I don't manage to fix it over the weekend, then on Monday I'll mark this as something for Galen to fix.

```
#!text

======================================================================
ERROR: test_autocal (test_algorithms.TestAlgorithms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fowlerj/Software/mass/src/mass/calibration/test_algorithms.py", line 147, in test_autocal
    auto_cal.autocal()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 293, in autocal
    self.fit_lines()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 279, in fit_lines
    mresult = multifit(self.ph, self.line_names, self.fit_lo_hi, self.binsize_ev, self.slopes_de_dph)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 199, in multifit
    fitter = singlefit(ph, name_e[i], lo, hi, binsize_ph, dP_dE)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 212, in singlefit
    counts, bin_edges = np.histogram(ph, np.arange(lo, hi, binsize_ph))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py", line 505, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

======================================================================
ERROR: test_complete (test_algorithms.TestAlgorithms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fowlerj/Software/mass/src/mass/calibration/test_algorithms.py", line 102, in test_complete
    fitters=multifit(ph, line_names, fit_lo_hi, np.ones_like(slopes_de_dph)*binsize_ev, slopes_de_dph)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 199, in multifit
    fitter = singlefit(ph, name_e[i], lo, hi, binsize_ph, dP_dE)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mass-0.5.0-py2.7-macosx-10.11-x86_64.egg/mass/calibration/algorithms.py", line 212, in singlefit
    counts, bin_edges = np.histogram(ph, np.arange(lo, hi, binsize_ph))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py", line 505, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.
```

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Tests of calibration algorithms: bug fixed.

Tests were generating random deviates from K-alpha and K-beta line
shape distributions. Often at least one energy would come out negative,
leading to NaN for the pulse heights and a failure of np.histogram(...)
to work properly on the PH data. Fixes #76.

Also changed so that the distribution.rvs() is called once with size=N
argument instead of N times without any arguments.
